version: '3'

services:
  clover-auth:
    image: "clover-auth"
    restart: always
    container_name: clover-auth
    volumes:
      - './config/auth:/go/server/configs'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8900/health" ]
      interval: 3s
      timeout: 5s
      retries: 6
    networks:
      - custom_net
    ports:
      - '8900:8900'

networks:
  custom_net:
    external:
      name: app_net