version: '3'

services:
  clover-auth:
    image: "clover-auth"
    restart: always
    container_name: clover-auth
    volumes:
      - './config/starter-auth:/go/clover/configs'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8810/health" ]
      interval: 3s
      timeout: 5s
      retries: 6
    networks:
      - app_net
    ports:
      - '8810:8810'

networks:
  app_net:
    external: true