@startuml

collections "接入权限的服务"
participant "starter-auth(权限中心)"
database "auth数据库"

"接入权限的服务" -> "starter-auth(权限中心)" : \
创建租户Token接口

"starter-auth(权限中心)" -> "starter-auth(权限中心)" : \
验证租户密钥1：超管租户验证

"starter-auth(权限中心)" -> "auth数据库" : \
查询普通租户表

"starter-auth(权限中心)" <- "auth数据库" : \
返回普通租户信息

"starter-auth(权限中心)" -> "starter-auth(权限中心)" : \
验证租户密钥2：普通租户管理员验证

"starter-auth(权限中心)" -> "starter-auth(权限中心)" : \
生成Token

"接入权限的服务" <- "starter-auth(权限中心)" : \
响应租户Token

@enduml