@startuml

collections "依赖权限的服务"
participant "starter-auth(权限中心)"
database "auth数据库"

"依赖权限的服务" -> "starter-auth(权限中心)" : \
创建用户接口

"starter-auth(权限中心)" -> "auth数据库" : \
查询用户信息

"starter-auth(权限中心)" <- "auth数据库" : \
返回用户信息

"starter-auth(权限中心)" -> "starter-auth(权限中心)" : \
验证用户是否存在\n\
存在则响应：用户已存在

"starter-auth(权限中心)" -> "auth数据库" : \
新增用户信息

"starter-auth(权限中心)" <- "auth数据库" : \
返回用户ID

"依赖权限的服务" <- "starter-auth(权限中心)" : \
响应用户ID

@enduml