@startuml

participant "接入平台的前端页"
participant "权限中心登录页"
participant "starter-auth(权限中心)"
database "auth数据库"
database "redis"

"接入平台的前端页" -> "权限中心登录页" : \
未登录的请求自动重定向

"权限中心登录页" -> "starter-auth(权限中心)" : \
获取用户登录授权码接口

"starter-auth(权限中心)" -> "auth数据库" : \
查询用户信息

"starter-auth(权限中心)" <- "auth数据库" : \
返回用户信息

"starter-auth(权限中心)" -> "starter-auth(权限中心)" : \
验证用户密码\n\
不匹配则响应：登陆失败\n\
创建授权码

"starter-auth(权限中心)" --> "redis" : \
异步：缓存授权码关联的用户信息60s

"权限中心登录页" <- "starter-auth(权限中心)" : \
响应授权码和重定向页面

"接入平台的前端页" <- "权限中心登录页"   : \
重定向到接入服务指定的前端页\n\
在请求路径中带上用户登录授权码\n\
路径如：https://www.xxx.com/?aucoCode=xxxxxxxxxxxx

@enduml