//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package repo

import (
	contextx "context"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
	allimpls "github.com/alibaba/ioc-golang/extension/autowire/allimpls"
	"github.com/zhanjunjie2019/clover/global/defs"
	"github.com/zhanjunjie2019/clover/starter-example/bc/infr/repo/po"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &exampleEntity1Repo_{}
		},
	})
	exampleEntity1RepoStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ExampleEntity1Repo{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(defs.IRepo),
					},
				},
			},
		},
	}
	singleton.RegisterStructDescriptor(exampleEntity1RepoStructDescriptor)
	allimpls.RegisterStructDescriptor(exampleEntity1RepoStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &exampleEntity2Repo_{}
		},
	})
	exampleEntity2RepoStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ExampleEntity2Repo{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(defs.IRepo),
					},
				},
			},
		},
	}
	singleton.RegisterStructDescriptor(exampleEntity2RepoStructDescriptor)
	allimpls.RegisterStructDescriptor(exampleEntity2RepoStructDescriptor)
}

type exampleEntity1Repo_ struct {
	AutoMigrate_ func(ctx contextx.Context) error
	Save_        func(ctx contextx.Context, entity1 po.ExampleEntity1) (id defs.ID, err error)
}

func (e *exampleEntity1Repo_) AutoMigrate(ctx contextx.Context) error {
	return e.AutoMigrate_(ctx)
}

func (e *exampleEntity1Repo_) Save(ctx contextx.Context, entity1 po.ExampleEntity1) (id defs.ID, err error) {
	return e.Save_(ctx, entity1)
}

type exampleEntity2Repo_ struct {
	AutoMigrate_ func(ctx contextx.Context) error
	Save_        func(ctx contextx.Context, entity2 po.ExampleEntity2) (id defs.ID, err error)
}

func (e *exampleEntity2Repo_) AutoMigrate(ctx contextx.Context) error {
	return e.AutoMigrate_(ctx)
}

func (e *exampleEntity2Repo_) Save(ctx contextx.Context, entity2 po.ExampleEntity2) (id defs.ID, err error) {
	return e.Save_(ctx, entity2)
}

type ExampleEntity1RepoIOCInterface interface {
	AutoMigrate(ctx contextx.Context) error
	Save(ctx contextx.Context, entity1 po.ExampleEntity1) (id defs.ID, err error)
}

type ExampleEntity2RepoIOCInterface interface {
	AutoMigrate(ctx contextx.Context) error
	Save(ctx contextx.Context, entity2 po.ExampleEntity2) (id defs.ID, err error)
}

var _exampleEntity1RepoSDID string

func GetExampleEntity1RepoSingleton() (*ExampleEntity1Repo, error) {
	if _exampleEntity1RepoSDID == "" {
		_exampleEntity1RepoSDID = util.GetSDIDByStructPtr(new(ExampleEntity1Repo))
	}
	i, err := singleton.GetImpl(_exampleEntity1RepoSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*ExampleEntity1Repo)
	return impl, nil
}

func GetExampleEntity1RepoIOCInterfaceSingleton() (ExampleEntity1RepoIOCInterface, error) {
	if _exampleEntity1RepoSDID == "" {
		_exampleEntity1RepoSDID = util.GetSDIDByStructPtr(new(ExampleEntity1Repo))
	}
	i, err := singleton.GetImplWithProxy(_exampleEntity1RepoSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ExampleEntity1RepoIOCInterface)
	return impl, nil
}

type ThisExampleEntity1Repo struct {
}

func (t *ThisExampleEntity1Repo) This() ExampleEntity1RepoIOCInterface {
	thisPtr, _ := GetExampleEntity1RepoIOCInterfaceSingleton()
	return thisPtr
}

var _exampleEntity2RepoSDID string

func GetExampleEntity2RepoSingleton() (*ExampleEntity2Repo, error) {
	if _exampleEntity2RepoSDID == "" {
		_exampleEntity2RepoSDID = util.GetSDIDByStructPtr(new(ExampleEntity2Repo))
	}
	i, err := singleton.GetImpl(_exampleEntity2RepoSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*ExampleEntity2Repo)
	return impl, nil
}

func GetExampleEntity2RepoIOCInterfaceSingleton() (ExampleEntity2RepoIOCInterface, error) {
	if _exampleEntity2RepoSDID == "" {
		_exampleEntity2RepoSDID = util.GetSDIDByStructPtr(new(ExampleEntity2Repo))
	}
	i, err := singleton.GetImplWithProxy(_exampleEntity2RepoSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ExampleEntity2RepoIOCInterface)
	return impl, nil
}

type ThisExampleEntity2Repo struct {
}

func (t *ThisExampleEntity2Repo) This() ExampleEntity2RepoIOCInterface {
	thisPtr, _ := GetExampleEntity2RepoIOCInterfaceSingleton()
	return thisPtr
}
