//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package gatewayimpl

import (
	contextx "context"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
	"github.com/zhanjunjie2019/clover/starter-generation/bc/generation/domain/model"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &generationGateway_{}
		},
	})
	generationGatewayStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &GenerationGateway{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(generationGatewayStructDescriptor)
}

type generationGateway_ struct {
	ModuleGen_ func(ctx contextx.Context, module model.Module) error
}

func (g *generationGateway_) ModuleGen(ctx contextx.Context, module model.Module) error {
	return g.ModuleGen_(ctx, module)
}

type GenerationGatewayIOCInterface interface {
	ModuleGen(ctx contextx.Context, module model.Module) error
}

var _generationGatewaySDID string

func GetGenerationGatewaySingleton() (*GenerationGateway, error) {
	if _generationGatewaySDID == "" {
		_generationGatewaySDID = util.GetSDIDByStructPtr(new(GenerationGateway))
	}
	i, err := singleton.GetImpl(_generationGatewaySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*GenerationGateway)
	return impl, nil
}

func GetGenerationGatewayIOCInterfaceSingleton() (GenerationGatewayIOCInterface, error) {
	if _generationGatewaySDID == "" {
		_generationGatewaySDID = util.GetSDIDByStructPtr(new(GenerationGateway))
	}
	i, err := singleton.GetImplWithProxy(_generationGatewaySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(GenerationGatewayIOCInterface)
	return impl, nil
}

type ThisGenerationGateway struct {
}

func (t *ThisGenerationGateway) This() GenerationGatewayIOCInterface {
	thisPtr, _ := GetGenerationGatewayIOCInterfaceSingleton()
	return thisPtr
}
