receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

processors:

extensions:
  health_check: { }

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "clover"

service:
  extensions: [ health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ jaeger ]

    metrics:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ prometheus ]
