//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package gatewayimpl

import (
	contextx "context"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
	"github.com/zhanjunjie2019/clover/global/defs"
	"github.com/zhanjunjie2019/clover/share/example/protobuf"
	"github.com/zhanjunjie2019/clover/starter-example/bc/domain/model"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &exampleGateway_{}
		},
	})
	exampleGatewayStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ExampleGateway{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(exampleGatewayStructDescriptor)
}

type exampleGateway_ struct {
	SaveExample1_        func(ctx contextx.Context, entity1 model.Entity1) (id defs.ID, err error)
	PublishEventMessage_ func(ctx contextx.Context, dto protobuf.ExampleDTO) error
}

func (e *exampleGateway_) SaveExample1(ctx contextx.Context, entity1 model.Entity1) (id defs.ID, err error) {
	return e.SaveExample1_(ctx, entity1)
}

func (e *exampleGateway_) PublishEventMessage(ctx contextx.Context, dto protobuf.ExampleDTO) error {
	return e.PublishEventMessage_(ctx, dto)
}

type ExampleGatewayIOCInterface interface {
	SaveExample1(ctx contextx.Context, entity1 model.Entity1) (id defs.ID, err error)
	PublishEventMessage(ctx contextx.Context, dto protobuf.ExampleDTO) error
}

var _exampleGatewaySDID string

func GetExampleGatewaySingleton() (*ExampleGateway, error) {
	if _exampleGatewaySDID == "" {
		_exampleGatewaySDID = util.GetSDIDByStructPtr(new(ExampleGateway))
	}
	i, err := singleton.GetImpl(_exampleGatewaySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*ExampleGateway)
	return impl, nil
}

func GetExampleGatewayIOCInterfaceSingleton() (ExampleGatewayIOCInterface, error) {
	if _exampleGatewaySDID == "" {
		_exampleGatewaySDID = util.GetSDIDByStructPtr(new(ExampleGateway))
	}
	i, err := singleton.GetImplWithProxy(_exampleGatewaySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ExampleGatewayIOCInterface)
	return impl, nil
}

type ThisExampleGateway struct {
}

func (t *ThisExampleGateway) This() ExampleGatewayIOCInterface {
	thisPtr, _ := GetExampleGatewayIOCInterfaceSingleton()
	return thisPtr
}
