version: '3'

services:
  nsqlookupd:
    image: "nsqio/nsq"
    container_name: 'nsqlookupd'
    restart: always
    command: "/nsqlookupd"
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - app_net

  nsqd:
    image: "nsqio/nsq"
    container_name: 'nsqd'
    restart: always
    command: "/nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd"
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    networks:
      - app_net

  nsqadmin:
    image: "nsqio/nsq"
    container_name: 'nsqadmin'
    restart: always
    command: "/nsqadmin --lookupd-http-address=nsqlookupd:4161"
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    networks:
      - app_net

networks:
  app_net:
    external: true
