//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package configs

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	allimpls "github.com/alibaba/ioc-golang/extension/autowire/allimpls"
	"github.com/zhanjunjie2019/clover/global/defs"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &exampleConfigDefine_{}
		},
	})
	exampleConfigDefineStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ExampleConfigDefine{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(defs.IConfigDefine),
					},
				},
			},
		},
	}
	allimpls.RegisterStructDescriptor(exampleConfigDefineStructDescriptor)
	var _ defs.IConfigDefine = &ExampleConfigDefine{}
}

type exampleConfigDefine_ struct {
	GetOption_    func() defs.ConfigOptions
	ReloadConfig_ func(config any) error
	Unmarshal_    func(data []byte) (any, error)
}

func (e *exampleConfigDefine_) GetOption() defs.ConfigOptions {
	return e.GetOption_()
}

func (e *exampleConfigDefine_) ReloadConfig(config any) error {
	return e.ReloadConfig_(config)
}

func (e *exampleConfigDefine_) Unmarshal(data []byte) (any, error) {
	return e.Unmarshal_(data)
}

type ExampleConfigDefineIOCInterface interface {
	GetOption() defs.ConfigOptions
	ReloadConfig(config any) error
	Unmarshal(data []byte) (any, error)
}

var _exampleConfigDefineSDID string
