version: '3.2'

services:

  filebeat:
    container_name: 'filebeat'
    restart: always
    image: 'docker.elastic.co/beats/filebeat:7.17.6'
    privileged: true
    user: root
    volumes:
      - './config/filebeat.yml:/usr/share/filebeat/filebeat.yml'
      - './logs:/var/logs'
    networks:
      - app_net

networks:
  app_net:
    external: true