version: '3'

services:
  consul:
    image: "bitnami/consul"
    restart: always
    container_name: "consul"
    volumes:
      - './data:/bitnami/consul'
    networks:
      - app_net
    environment:
      - "CONSUL_DISABLE_KEYRING_FILE=true"
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8500:8500'
      - '8600:8600'

networks:
  app_net:
    external: true