version: '3.2'

services:
  elasticsearch:
    container_name: 'elasticsearch'
    restart: always
    image: 'bitnami/elasticsearch:7.17.6'
    privileged: true
    user: root
    volumes:
      - type: bind
        source: './data'
        target: '/bitnami/elasticsearch/data'
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "9200:9200"
    networks:
      - custom_net

  kibana:
    container_name: 'kibana'
    restart: always
    image: 'bitnami/kibana:7.17.6'
    volumes:
      - type: bind
        source: './config'
        target: '/opt/bitnami/kibana/conf'
    ports:
      - "5601:5601"
    networks:
      - custom_net
    depends_on:
      - elasticsearch
      
networks:
  custom_net:
   external:
      name: app_net