version: "3"
services:
  prometheus:
    container_name: "prometheus"
    image: "prom/prometheus:latest"
    restart: always
    volumes:
      - "./config/prometheus.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - app_net

networks:
  app_net:
    external: true