//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package uorm

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
	"gorm.io/gorm"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &dBFactory_{}
		},
	})
	dBFactoryStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &DBFactory{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(dBFactoryStructDescriptor)
}

type dBFactory_ struct {
	GetDB_ func() (*gorm.DB, error)
}

func (d *dBFactory_) GetDB() (*gorm.DB, error) {
	return d.GetDB_()
}

type DBFactoryIOCInterface interface {
	GetDB() (*gorm.DB, error)
}

var _dBFactorySDID string

func GetDBFactorySingleton() (*DBFactory, error) {
	if _dBFactorySDID == "" {
		_dBFactorySDID = util.GetSDIDByStructPtr(new(DBFactory))
	}
	i, err := singleton.GetImpl(_dBFactorySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*DBFactory)
	return impl, nil
}

func GetDBFactoryIOCInterfaceSingleton() (DBFactoryIOCInterface, error) {
	if _dBFactorySDID == "" {
		_dBFactorySDID = util.GetSDIDByStructPtr(new(DBFactory))
	}
	i, err := singleton.GetImplWithProxy(_dBFactorySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(DBFactoryIOCInterface)
	return impl, nil
}
