//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package consumer

import (
	contextx "context"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	allimpls "github.com/alibaba/ioc-golang/extension/autowire/allimpls"
	defs "github.com/zhanjunjie2019/clover/global/defs"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &helloWordConsumer_{}
		},
	})
	helloWordConsumerStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &HelloWordConsumer{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(defs.IConsumer),
					},
				},
			},
		},
	}
	allimpls.RegisterStructDescriptor(helloWordConsumerStructDescriptor)
}

type helloWordConsumer_ struct {
	GetTopic_      func() string
	HandleMessage_ func(ctx contextx.Context, bytes []byte) error
}

func (h *helloWordConsumer_) GetTopic() string {
	return h.GetTopic_()
}

func (h *helloWordConsumer_) HandleMessage(ctx contextx.Context, bytes []byte) error {
	return h.HandleMessage_(ctx, bytes)
}

type HelloWordConsumerIOCInterface interface {
	GetTopic() string
	HandleMessage(ctx contextx.Context, bytes []byte) error
}

var _helloWordConsumerSDID string
