// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tenant-create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "初始化租户",
                "parameters": [
                    {
                        "description": "初始化租户",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.TenantCreateReqVO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.TenantCreateRspVO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user-authorization-code": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录获得授权码，注意授权码不是Token，不能直接用于访问接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "租户ID",
                        "name": "Tenant-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户登录获得授权码，注意授权码不是Token，不能直接用于访问接口",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.UserAuthorizationCodeReqVO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.UserAuthorizationCodeRspVO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码：成功[0],底层的错误[1000-1999],平台层级的错误[2000-2999]",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "详细信息",
                    "type": "string"
                }
            }
        },
        "vo.TenantCreateReqVO": {
            "type": "object",
            "required": [
                "tenantName"
            ],
            "properties": {
                "tenantID": {
                    "description": "租户ID，不传默认则随机生成",
                    "type": "string"
                },
                "tenantName": {
                    "description": "租户名",
                    "type": "string"
                }
            }
        },
        "vo.TenantCreateRspVO": {
            "type": "object",
            "properties": {
                "secretKey": {
                    "description": "租户密钥",
                    "type": "string"
                },
                "tenantID": {
                    "description": "租户ID",
                    "type": "string"
                }
            }
        },
        "vo.UserAuthorizationCodeReqVO": {
            "type": "object",
            "required": [
                "password",
                "userName"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "redirectUrl": {
                    "description": "重定向路径，可选，若无按租户设置",
                    "type": "string"
                },
                "userName": {
                    "description": "账户名",
                    "type": "string"
                }
            }
        },
        "vo.UserAuthorizationCodeRspVO": {
            "type": "object",
            "properties": {
                "authorizationCode": {
                    "description": "授权码",
                    "type": "string"
                },
                "redirectUrl": {
                    "description": "重定向路径",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "",
	BasePath:         "/auth",
	Schemes:          []string{},
	Title:            "clover-auth-api",
	Description:      "clover-auth接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
