definitions:
  response.Response:
    properties:
      code:
        description: 错误码：成功[0],底层的错误[1000-1999],平台层级的错误[2000-2999]
        type: integer
      data:
        description: 数据
      msg:
        description: 详细信息
        type: string
    type: object
  vo.PermissionInfoVO:
    properties:
      auth_code:
        description: 资源编码
        type: string
      permission_name:
        description: 许可名称
        type: string
    required:
    - auth_code
    - permission_name
    type: object
  vo.PermissionReqVO:
    properties:
      permissions:
        items:
          $ref: '#/definitions/vo.PermissionInfoVO'
        type: array
    required:
    - permissions
    type: object
  vo.PermissionRspVO:
    properties:
      permission_ids:
        description: 许可ID
        items:
          type: integer
        type: array
    type: object
  vo.RoleCreateReqVO:
    properties:
      roles:
        items:
          $ref: '#/definitions/vo.RoleInfoVO'
        type: array
    required:
    - roles
    type: object
  vo.RoleCreateRspVO:
    properties:
      role_ids:
        description: 角色ID
        items:
          type: integer
        type: array
    type: object
  vo.RoleInfoVO:
    properties:
      role_code:
        description: 角色编码
        type: string
      role_name:
        description: 角色名
        type: string
    required:
    - role_code
    - role_name
    type: object
  vo.RolePermissionAssignmentReqVO:
    properties:
      auth_codes:
        description: 资源编码
        items:
          type: string
        type: array
      role_code:
        description: 角色编码，与角色ID二选一
        type: string
      role_id:
        description: 角色ID，与角色编码二选一
        type: integer
    required:
    - auth_codes
    type: object
  vo.RolePermissionAssignmentRspVO:
    properties:
      role_id:
        description: 角色ID
        type: integer
    type: object
  vo.SadminTokenCreateReqVO:
    properties:
      secret_key:
        description: 租户密钥
        type: string
    required:
    - secret_key
    type: object
  vo.SadminTokenCreateRspVO:
    properties:
      access_token:
        description: 访问Token
        type: string
      access_token_expiration_time:
        description: 访问Token过期时间戳
        type: integer
    type: object
  vo.TenantCreateReqVO:
    properties:
      tenants:
        items:
          $ref: '#/definitions/vo.TenantInfoVO'
        type: array
    required:
    - tenants
    type: object
  vo.TenantCreateRspVO:
    properties:
      secret_keys:
        items:
          $ref: '#/definitions/vo.TenantSecretKeyVO'
        type: array
    type: object
  vo.TenantInfoVO:
    properties:
      access_token_time_limit:
        description: 访问Token有效时限，非必要，默认7200s
        type: integer
      redirect_url:
        description: 授权码重定向路径，非必要
        type: string
      tenant_id:
        description: 租户ID，非必要，不传默认则随机生成，英文字母，长度小于{20}位
        maxLength: 20
        type: string
      tenant_name:
        description: 租户名
        type: string
    required:
    - tenant_name
    type: object
  vo.TenantSecretKeyVO:
    properties:
      secret_key:
        description: 租户密钥
        type: string
      tenant_id:
        description: 租户ID
        type: string
    type: object
  vo.TenantTokenCreateReqVO:
    properties:
      access_token_expiration_time:
        description: 访问Token过期时间戳，非必要，不传则按当前时间+戳追加租户设置有效时限
        type: integer
      secret_key:
        description: 租户密钥
        type: string
      tenant_id:
        description: 租户ID
        type: string
    required:
    - secret_key
    - tenant_id
    type: object
  vo.TenantTokenCreateRspVO:
    properties:
      access_token:
        description: 访问Token
        type: string
      access_token_expiration_time:
        description: 访问Token过期时间戳
        type: integer
    type: object
  vo.UserAuthorizationCodeReqVO:
    properties:
      password:
        description: 密码
        type: string
      user_name:
        description: 账户名
        type: string
    required:
    - password
    - user_name
    type: object
  vo.UserAuthorizationCodeRspVO:
    properties:
      authorization_code:
        description: 授权码
        type: string
      redirect_url:
        description: 重定向路径
        type: string
    type: object
  vo.UserCreateReqVO:
    properties:
      users:
        items:
          $ref: '#/definitions/vo.UserInfoVO'
        type: array
    required:
    - users
    type: object
  vo.UserCreateRspVO:
    properties:
      user_ids:
        description: 用户ID
        items:
          type: integer
        type: array
    type: object
  vo.UserInfoVO:
    properties:
      password:
        description: 密码
        type: string
      user_name:
        description: 用户名
        type: string
    required:
    - password
    - user_name
    type: object
  vo.UserRoleAssignmentReqVO:
    properties:
      role_codes:
        description: 角色编码
        items:
          type: string
        type: array
      user_id:
        description: 用户ID，与用户名二选一
        type: integer
      user_name:
        description: 用户名，与用户ID二选一
        type: string
    required:
    - role_codes
    type: object
  vo.UserRoleAssignmentRspVO:
    properties:
      user_id:
        description: 用户ID
        type: integer
    type: object
  vo.UserTokenByAuthcodeReqVO:
    properties:
      authorization_code:
        description: 授权码
        type: string
    required:
    - authorization_code
    type: object
  vo.UserTokenByAuthcodeRspVO:
    properties:
      access_token:
        description: 访问Token
        type: string
      access_token_expiration_time:
        description: 访问Token过期时间戳
        type: integer
    type: object
info:
  contact: {}
  description: clover-auth接口文档
  title: clover-auth-api
  version: v1.0.0
paths:
  /auth/permission-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建资源权限许可
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.PermissionReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.PermissionRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建资源权限许可
      tags:
      - permission
  /auth/role-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 创建角色
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.RoleCreateReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.RoleCreateRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建角色，需要租户管理员权限
      tags:
      - role
  /auth/role-permission-assignment:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 角色赋予资源许可
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.RolePermissionAssignmentReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.RolePermissionAssignmentRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 角色赋予资源许可，需要租户管理员权限
      tags:
      - role
  /auth/sadmin-token-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 获得超管Token
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.SadminTokenCreateReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.SadminTokenCreateRspVO'
              type: object
      summary: 获得超管Token
      tags:
      - sadmin
  /auth/tenant-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建租户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.TenantCreateReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.TenantCreateRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建租户
      tags:
      - tenant
  /auth/tenant-token-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建租户Token
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.TenantTokenCreateReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.TenantTokenCreateRspVO'
              type: object
      summary: 创建租户Token
      tags:
      - tenant
  /auth/user-authorization-code:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 用户登录获得授权码，注意授权码不是Token，不能直接用于访问接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.UserAuthorizationCodeReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.UserAuthorizationCodeRspVO'
              type: object
      summary: 登录验证用户账号密码，验证通过后授权码60秒有效，关联用户信息。可以用授权码接口换取登录Token。
      tags:
      - user
  /auth/user-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 创建用户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.UserCreateReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.UserCreateRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建用户，需要租户管理员权限
      tags:
      - user
  /auth/user-role-assignment:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 用户赋予角色
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.UserRoleAssignmentReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.UserRoleAssignmentRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 用户赋予角色，需要租户管理员权限
      tags:
      - user
  /auth/user-token-by-authcode:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 使用授权码获取用户token信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.UserTokenByAuthcodeReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.UserTokenByAuthcodeRspVO'
              type: object
      summary: 使用授权码获取用户token信息
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: C-Token
    type: apiKey
swagger: "2.0"
