basePath: /auth
definitions:
  response.Response:
    properties:
      code:
        description: 错误码：成功[0],底层的错误[1000-1999],平台层级的错误[2000-2999]
        type: integer
      data:
        description: 数据
      msg:
        description: 详细信息
        type: string
    type: object
  vo.PermissionReqVO:
    properties:
      authCode:
        description: 资源编码
        type: string
      permissionName:
        description: 许可名称
        type: string
    required:
    - authCode
    - permissionName
    type: object
  vo.PermissionRspVO:
    properties:
      permissionId:
        description: 许可ID
        type: integer
    type: object
  vo.RoleCreateReqVO:
    properties:
      roleCode:
        description: 角色编码
        type: string
      roleName:
        description: 角色名
        type: string
    required:
    - roleCode
    - roleName
    type: object
  vo.RoleCreateRspVO:
    properties:
      roleId:
        description: 角色ID
        type: integer
    type: object
  vo.RolePermissionAssignmentReqVO:
    properties:
      authCodes:
        description: 资源编码
        items:
          type: string
        type: array
      roleCode:
        description: 角色编码
        type: string
    required:
    - authCodes
    - roleCode
    type: object
  vo.RolePermissionAssignmentRspVO:
    properties:
      roleId:
        description: 角色ID
        type: integer
    type: object
  vo.TenantCreateReqVO:
    properties:
      AccessTokenTimeLimit:
        description: 访问Token有效时限，非必要，默认7200s
        type: integer
      redirectUrl:
        description: 授权码重定向路径，非必要
        type: string
      tenantID:
        description: 租户ID，非必要，不传默认则随机生成
        type: string
      tenantName:
        description: 租户名
        type: string
    required:
    - tenantName
    type: object
  vo.TenantCreateRspVO:
    properties:
      secretKey:
        description: 租户密钥
        type: string
      tenantID:
        description: 租户ID
        type: string
    type: object
  vo.TenantTokenCreateReqVO:
    properties:
      accessTokenExpirationTime:
        description: 访问Token过期时间戳，非必要，不传则按当前时间+戳追加租户设置有效时限
        type: integer
      secretKey:
        description: 租户密钥
        type: string
      tenantID:
        description: 租户ID
        type: string
    required:
    - secretKey
    - tenantID
    type: object
  vo.TenantTokenCreateRspVO:
    properties:
      accessToken:
        description: 访问Token
        type: string
      accessTokenExpirationTime:
        description: 访问Token过期时间戳
        type: integer
    type: object
  vo.UserAuthorizationCodeReqVO:
    properties:
      password:
        description: 密码
        type: string
      redirectUrl:
        description: 重定向路径，非必要，不传则按租户设置
        type: string
      userName:
        description: 账户名
        type: string
    required:
    - password
    - userName
    type: object
  vo.UserAuthorizationCodeRspVO:
    properties:
      authorizationCode:
        description: 授权码
        type: string
      redirectUrl:
        description: 重定向路径
        type: string
    type: object
  vo.UserCreateReqVO:
    properties:
      password:
        description: 密码
        type: string
      userName:
        description: 用户名
        type: string
    required:
    - password
    - userName
    type: object
  vo.UserCreateRspVO:
    properties:
      userId:
        description: 用户ID
        type: integer
    type: object
  vo.UserRoleAssignmentReqVO:
    type: object
  vo.UserRoleAssignmentRspVO:
    type: object
info:
  contact: {}
  description: clover-auth接口文档
  title: clover-auth-api
  version: v1.0.0
paths:
  /permission-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 创建资源权限许可
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.PermissionReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.PermissionRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建资源权限许可
      tags:
      - permission
  /role-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 创建角色
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.RoleCreateReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.RoleCreateRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建角色，需要租户管理员权限
      tags:
      - role
  /role-permission-assignment:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 角色赋予资源许可
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.RolePermissionAssignmentReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.RolePermissionAssignmentRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 角色赋予资源许可，需要租户管理员权限
      tags:
      - role
  /tenant-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 创建租户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.TenantCreateReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.TenantCreateRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建租户
      tags:
      - tenant
  /tenant-token-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建租户Token
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.TenantTokenCreateReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.TenantTokenCreateRspVO'
              type: object
      summary: 创建租户Token
      tags:
      - tenant
  /user-authorization-code:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 用户登录获得授权码，注意授权码不是Token，不能直接用于访问接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.UserAuthorizationCodeReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.UserAuthorizationCodeRspVO'
              type: object
      summary: 登录验证用户账号密码，验证通过后授权码60秒有效，关联用户信息。可以用授权码接口换取登录Token。
      tags:
      - user
  /user-create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 创建用户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.UserCreateReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.UserCreateRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建用户，需要租户管理员权限
      tags:
      - user
  /user-role-assignment:
    post:
      consumes:
      - application/json
      parameters:
      - description: 租户ID
        in: header
        name: Tenant-ID
        required: true
        type: string
      - description: 用户赋予角色
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/vo.UserRoleAssignmentReqVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.UserRoleAssignmentRspVO'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 用户赋予角色，需要租户管理员权限
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: C-Token
    type: apiKey
swagger: "2.0"
