version: '3'
services:
  postgres-master:
    image: 'bitnami/postgresql'
    restart: always
    container_name: 'postgres-master'
    privileged: true
    user: root
    environment:
      - 'TZ=Asia/Shanghai'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRESQL_POSTGRES_PASSWORD=123456'
      - 'POSTGRES_DB=clover'
      - 'POSTGRESQL_REPLICATION_MODE=master'
      - 'POSTGRESQL_REPLICATION_USER=clover'
      - 'POSTGRESQL_REPLICATION_PASSWORD=clover'
      - 'POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on'
      - 'POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1'
    ports:
      - '9432:5432'
    networks:
      - app_net
    volumes:
      - './master:/bitnami/postgresql'
      - './init:/docker-entrypoint-initdb.d'
  postgres-slave:
    image: 'bitnami/postgresql'
    restart: always
    container_name: 'postgres-slave'
    privileged: true
    user: root
    environment:
      - 'TZ=Asia/Shanghai'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRESQL_POSTGRES_PASSWORD=123456'
      - 'POSTGRES_DB=clover'
      - 'POSTGRESQL_REPLICATION_MODE=slave'
      - 'POSTGRESQL_REPLICATION_USER=clover'
      - 'POSTGRESQL_REPLICATION_PASSWORD=clover'
      - 'POSTGRESQL_MASTER_HOST=postgres-master'
      - 'POSTGRESQL_MASTER_PORT_NUMBER=5432'
    links:
      - 'postgres-master'
    ports:
      - '9433:5432'
    networks:
      - app_net
    volumes:
      - './slave:/bitnami/postgresql'

networks:
  app_net:
    external: true
