// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nsqd.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NsqMessage struct {
	// 链路信息
	TraceId string `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	// 链路信息
	TraceSpanID string `protobuf:"bytes,2,opt,name=traceSpanID,proto3" json:"traceSpanID,omitempty"`
	// 消息内容
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// 签名验证
	Sign                 string   `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NsqMessage) Reset()         { *m = NsqMessage{} }
func (m *NsqMessage) String() string { return proto.CompactTextString(m) }
func (*NsqMessage) ProtoMessage()    {}
func (*NsqMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5854dde9139d1e28, []int{0}
}

func (m *NsqMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NsqMessage.Unmarshal(m, b)
}
func (m *NsqMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NsqMessage.Marshal(b, m, deterministic)
}
func (m *NsqMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NsqMessage.Merge(m, src)
}
func (m *NsqMessage) XXX_Size() int {
	return xxx_messageInfo_NsqMessage.Size(m)
}
func (m *NsqMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NsqMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NsqMessage proto.InternalMessageInfo

func (m *NsqMessage) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *NsqMessage) GetTraceSpanID() string {
	if m != nil {
		return m.TraceSpanID
	}
	return ""
}

func (m *NsqMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *NsqMessage) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func init() {
	proto.RegisterType((*NsqMessage)(nil), "protobuf.NsqMessage")
}

func init() {
	proto.RegisterFile("nsqd.proto", fileDescriptor_5854dde9139d1e28)
}

var fileDescriptor_5854dde9139d1e28 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2b, 0x2e, 0x4c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x05, 0x5c,
	0x5c, 0x7e, 0xc5, 0x85, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0x25,
	0x45, 0x89, 0xc9, 0xa9, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90,
	0x02, 0x17, 0x37, 0x98, 0x19, 0x5c, 0x90, 0x98, 0xe7, 0xe9, 0x22, 0xc1, 0x04, 0x96, 0x45, 0x16,
	0x12, 0x12, 0xe2, 0x62, 0x49, 0xca, 0x4f, 0xa9, 0x94, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x09, 0x02,
	0xb3, 0x41, 0x62, 0xc5, 0x99, 0xe9, 0x79, 0x12, 0x2c, 0x60, 0xe5, 0x60, 0x76, 0x12, 0x1b, 0xd8,
	0x6e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0x84, 0x5c, 0x9f, 0x90, 0x00, 0x00, 0x00,
}
