definitions:
  response.Response:
    properties:
      code:
        description: 错误码：成功[0],底层的错误[1000-1999],平台层级的错误[2000-2999]
        type: integer
      data:
        description: 数据
      msg:
        description: 详细信息
        type: string
    type: object
  vo.DomainAggregationVO:
    properties:
      aggregationRoot:
        $ref: '#/definitions/vo.DomainEntityVO'
        description: 聚合根
    type: object
  vo.DomainBoundedContextVO:
    properties:
      aggregations:
        description: 领域聚合
        items:
          $ref: '#/definitions/vo.DomainAggregationVO'
        type: array
    required:
    - aggregations
    type: object
  vo.DomainEntityVO:
    properties:
      ValueObjects:
        description: 值对象
        items:
          $ref: '#/definitions/vo.DomainValueObjectVO'
        type: array
      entityName:
        description: 实体名，长度必须满足{2}~{30}位
        maxLength: 30
        minLength: 2
        type: string
      entitys:
        description: 实体
        items:
          $ref: '#/definitions/vo.DomainEntityVO'
        type: array
    required:
    - ValueObjects
    type: object
  vo.DomainValueObjectVO:
    properties:
      ValueObjects:
        description: 值对象
        items:
          $ref: '#/definitions/vo.DomainValueObjectVO'
        type: array
      valObjBaseType:
        description: 值基础类型，0=非基础值对象，1=string，2=uint8，3=uint16，4=uint32，5=uint64
        type: integer
      valObjName:
        description: 值对象名，长度必须满足{2}~{30}位
        maxLength: 30
        minLength: 2
        type: string
      valRelType:
        description: 值对象链接类型，1=一对一，其他=一对多
        type: integer
    type: object
  vo.ModuleGenRspVO:
    type: object
info:
  contact: {}
  description: clover-generation接口文档
  title: clover-generation-api
  version: v1.0.0
paths:
  /gen/module-gen:
    get:
      consumes:
      - application/json
      parameters:
      - description: 是否加载配置中心配置，1=是，其他=否
        in: query
        name: loadConfigByConsul
        type: integer
      - description: 是否启用遥测链路追踪，1=是，其他=否
        in: query
        name: loadOpenTelemetry
        type: integer
      - description: 模块名，必须满足英文字母{2}~{20}位
        in: query
        maxLength: 20
        minLength: 2
        name: moduleName
        type: string
      - description: 服务默认端口，0~65535
        in: query
        maximum: 65535
        name: serverPort
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.ModuleGenRspVO'
              type: object
      summary: 生成完整服务代码
      tags:
      - gen
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: C-Token
    type: apiKey
swagger: "2.0"
