version: "3"

services:
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    restart: always
    container_name: 'jaeger'
    environment:
#      - "SPAN_STORAGE_TYPE=badger"
#      - "BADGER_EPHEMERAL=false"
#      - "BADGER_DIRECTORY_VALUE=/badger/data"
#      - "BADGER_DIRECTORY_KEY=/badger/key"
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://elasticsearch:9200"
      - "METRICS_STORAGE_TYPE=prometheus"
      - "PROMETHEUS_SERVER_URL=http://prometheus:9090"
    volumes:
      - "./data:/badger"
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - custom_net

networks:
  custom_net:
   external:
      name: app_net