definitions:
  response.Response:
    properties:
      code:
        description: 错误码：成功[0],底层的错误[1000-1999],平台层级的错误[2000-2999]
        type: integer
      data:
        description: 数据
      msg:
        description: 详细信息
        type: string
    type: object
  vo.HelloWorldRspVO:
    properties:
      greetings:
        description: 问候语
        type: string
    type: object
info:
  contact: {}
  description: clover-example接口文档
  title: clover-example-api
  version: v1.0.0
paths:
  /example/hellow-world:
    get:
      consumes:
      - application/json
      parameters:
      - description: 姓，必填
        in: query
        name: firstName
        required: true
        type: string
      - description: 名，必填
        in: query
        name: lastName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.HelloWorldRspVO'
              type: object
      summary: 接口描述
      tags:
      - example
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: C-Token
    type: apiKey
swagger: "2.0"
