//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package app

import (
	contextx "context"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
	"github.com/zhanjunjie2019/clover/starter-example/bc/example/app/cmd"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &exampleApp_{}
		},
	})
	exampleAppStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ExampleApp{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(exampleAppStructDescriptor)
}

type exampleApp_ struct {
	ExampleHellowWorld_ func(ctx contextx.Context, c cmd.HelloWorldCmd) (rs cmd.HelloWorldResult, err error)
}

func (e *exampleApp_) ExampleHellowWorld(ctx contextx.Context, c cmd.HelloWorldCmd) (rs cmd.HelloWorldResult, err error) {
	return e.ExampleHellowWorld_(ctx, c)
}

type ExampleAppIOCInterface interface {
	ExampleHellowWorld(ctx contextx.Context, c cmd.HelloWorldCmd) (rs cmd.HelloWorldResult, err error)
}

var _exampleAppSDID string

func GetExampleAppSingleton() (*ExampleApp, error) {
	if _exampleAppSDID == "" {
		_exampleAppSDID = util.GetSDIDByStructPtr(new(ExampleApp))
	}
	i, err := singleton.GetImpl(_exampleAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*ExampleApp)
	return impl, nil
}

func GetExampleAppIOCInterfaceSingleton() (ExampleAppIOCInterface, error) {
	if _exampleAppSDID == "" {
		_exampleAppSDID = util.GetSDIDByStructPtr(new(ExampleApp))
	}
	i, err := singleton.GetImplWithProxy(_exampleAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ExampleAppIOCInterface)
	return impl, nil
}

type ThisExampleApp struct {
}

func (t *ThisExampleApp) This() ExampleAppIOCInterface {
	thisPtr, _ := GetExampleAppIOCInterfaceSingleton()
	return thisPtr
}
