//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package grpsvc

import (
	contextx "context"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	allimpls "github.com/alibaba/ioc-golang/extension/autowire/allimpls"
	defs "github.com/zhanjunjie2019/clover/global/defs"
	"github.com/zhanjunjie2019/clover/share/example/protobuf"
	"go-micro.dev/v4/server"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &exampleServiceHandler_{}
		},
	})
	exampleServiceHandlerStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ExampleServiceHandler{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(defs.IGrpcServiceHandler),
					},
				},
			},
		},
	}
	allimpls.RegisterStructDescriptor(exampleServiceHandlerStructDescriptor)
}

type exampleServiceHandler_ struct {
	GrpcRegister_ func(s server.Server) error
	HelloWorld_   func(ctx contextx.Context, reqVO *protobuf.ExampleGrpcReqVO, rspVO *protobuf.ExampleGrpcRspVO) error
}

func (e *exampleServiceHandler_) GrpcRegister(s server.Server) error {
	return e.GrpcRegister_(s)
}

func (e *exampleServiceHandler_) HelloWorld(ctx contextx.Context, reqVO *protobuf.ExampleGrpcReqVO, rspVO *protobuf.ExampleGrpcRspVO) error {
	return e.HelloWorld_(ctx, reqVO, rspVO)
}

type ExampleServiceHandlerIOCInterface interface {
	GrpcRegister(s server.Server) error
	HelloWorld(ctx contextx.Context, reqVO *protobuf.ExampleGrpcReqVO, rspVO *protobuf.ExampleGrpcRspVO) error
}

var _exampleServiceHandlerSDID string
