# redis配置
redisConfig:
  # 是否启用redis，1是2否
  enabled: 1
  # redis域名地址
  addr: "127.0.0.1:6379"
  # redis密码
  password: "clover"
  # redis子库
  db: 2
# jwt配置
jwtConfig:
  # 签名密钥
  signingKey: "clover"
  # 过期时限，单位秒
  expiresTime: 14400
# 遥测体系配置
otelConfig:
  # 是否启用遥测体系，1是2否
  enabled: 1
  # collector的GRPC端口
  collectorGrpcEndpoint: "127.0.0.1:4317"
nsqConfig:
  # 是否开启NSQ消息队列，1是2否
  enabled: 1
  # 用于生产者使用的nsqd服务地址
  producerAddr: "127.0.0.1:4150"
  # 用于消费者使用的nsqlookupd服务地址
  consumerAddr: "127.0.0.1:4161"
