//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package controller

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	allimpls "github.com/alibaba/ioc-golang/extension/autowire/allimpls"
	"github.com/gin-gonic/gin"
	"github.com/zhanjunjie2019/clover/global/defs"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &tenantCreateController_{}
		},
	})
	tenantCreateControllerStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &TenantCreateController{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(defs.IController),
					},
				},
			},
		},
	}
	allimpls.RegisterStructDescriptor(tenantCreateControllerStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &tenantTokenCreateController_{}
		},
	})
	tenantTokenCreateControllerStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &TenantTokenCreateController{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(defs.IController),
					},
				},
			},
		},
	}
	allimpls.RegisterStructDescriptor(tenantTokenCreateControllerStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &userAuthorizationCodeController_{}
		},
	})
	userAuthorizationCodeControllerStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &UserAuthorizationCodeController{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(defs.IController),
					},
				},
			},
		},
	}
	allimpls.RegisterStructDescriptor(userAuthorizationCodeControllerStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &userCreateController_{}
		},
	})
	userCreateControllerStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &UserCreateController{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(defs.IController),
					},
				},
			},
		},
	}
	allimpls.RegisterStructDescriptor(userCreateControllerStructDescriptor)
}

type tenantCreateController_ struct {
	GetOption_ func() defs.ControllerOption
	Handle_    func(c *gin.Context)
}

func (t *tenantCreateController_) GetOption() defs.ControllerOption {
	return t.GetOption_()
}

func (t *tenantCreateController_) Handle(c *gin.Context) {
	t.Handle_(c)
}

type tenantTokenCreateController_ struct {
	GetOption_ func() defs.ControllerOption
	Handle_    func(c *gin.Context)
}

func (t *tenantTokenCreateController_) GetOption() defs.ControllerOption {
	return t.GetOption_()
}

func (t *tenantTokenCreateController_) Handle(c *gin.Context) {
	t.Handle_(c)
}

type userAuthorizationCodeController_ struct {
	GetOption_ func() defs.ControllerOption
	Handle_    func(c *gin.Context)
}

func (u *userAuthorizationCodeController_) GetOption() defs.ControllerOption {
	return u.GetOption_()
}

func (u *userAuthorizationCodeController_) Handle(c *gin.Context) {
	u.Handle_(c)
}

type userCreateController_ struct {
	GetOption_ func() defs.ControllerOption
	Handle_    func(c *gin.Context)
}

func (u *userCreateController_) GetOption() defs.ControllerOption {
	return u.GetOption_()
}

func (u *userCreateController_) Handle(c *gin.Context) {
	u.Handle_(c)
}

type TenantCreateControllerIOCInterface interface {
	GetOption() defs.ControllerOption
	Handle(c *gin.Context)
}

type TenantTokenCreateControllerIOCInterface interface {
	GetOption() defs.ControllerOption
	Handle(c *gin.Context)
}

type UserAuthorizationCodeControllerIOCInterface interface {
	GetOption() defs.ControllerOption
	Handle(c *gin.Context)
}

type UserCreateControllerIOCInterface interface {
	GetOption() defs.ControllerOption
	Handle(c *gin.Context)
}

var _tenantCreateControllerSDID string
var _tenantTokenCreateControllerSDID string
var _userAuthorizationCodeControllerSDID string
var _userCreateControllerSDID string
