version: "3"
services:

  otel-collector:
    image: "otel/opentelemetry-collector-contrib:latest"
    restart: always
    container_name: 'otel-collector'
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - "./config/otel-collector-config.yml:/etc/otel-collector-config.yml"
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    networks:
      - custom_net

networks:
  custom_net:
    external:
      name: app_net