version: '3'

services:
  etcd:
    image: 'bitnami/etcd:latest'
    restart: always
    container_name: "etcd"
    volumes:
      - './data:/bitnami/etcd'
    networks:
      - app_net
    environment:
      - 'ALLOW_NONE_AUTHENTICATION=yes'
      - 'ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379'
    ports:
      - '2379:2379'
      - '2380:2380'

networks:
  app_net:
    external: true