//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package app

import (
	contextx "context"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
	"github.com/zhanjunjie2019/clover/starter-generation/bc/generation/app/cmd"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &generationApp_{}
		},
	})
	generationAppStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &GenerationApp{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(generationAppStructDescriptor)
}

type generationApp_ struct {
	ModuleGen_ func(ctx contextx.Context, c cmd.ModuleGenCmd) (rs cmd.ModuleGenResult, err error)
}

func (g *generationApp_) ModuleGen(ctx contextx.Context, c cmd.ModuleGenCmd) (rs cmd.ModuleGenResult, err error) {
	return g.ModuleGen_(ctx, c)
}

type GenerationAppIOCInterface interface {
	ModuleGen(ctx contextx.Context, c cmd.ModuleGenCmd) (rs cmd.ModuleGenResult, err error)
}

var _generationAppSDID string

func GetGenerationAppSingleton() (*GenerationApp, error) {
	if _generationAppSDID == "" {
		_generationAppSDID = util.GetSDIDByStructPtr(new(GenerationApp))
	}
	i, err := singleton.GetImpl(_generationAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*GenerationApp)
	return impl, nil
}

func GetGenerationAppIOCInterfaceSingleton() (GenerationAppIOCInterface, error) {
	if _generationAppSDID == "" {
		_generationAppSDID = util.GetSDIDByStructPtr(new(GenerationApp))
	}
	i, err := singleton.GetImplWithProxy(_generationAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(GenerationAppIOCInterface)
	return impl, nil
}

type ThisGenerationApp struct {
}

func (t *ThisGenerationApp) This() GenerationAppIOCInterface {
	thisPtr, _ := GetGenerationAppIOCInterfaceSingleton()
	return thisPtr
}
