//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package app

import (
	contextx "context"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
	"github.com/zhanjunjie2019/clover/global/defs"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &tenantCreateApp_{}
		},
	})
	tenantCreateAppStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &TenantCreateApp{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(tenantCreateAppStructDescriptor)
}

type tenantCreateApp_ struct {
	TenantCreate_ func(ctx contextx.Context, layout *defs.LogLayout, tenantID, tenantName string) (tid, secretKey string, err error)
}

func (t *tenantCreateApp_) TenantCreate(ctx contextx.Context, layout *defs.LogLayout, tenantID, tenantName string) (tid, secretKey string, err error) {
	return t.TenantCreate_(ctx, layout, tenantID, tenantName)
}

type TenantCreateAppIOCInterface interface {
	TenantCreate(ctx contextx.Context, layout *defs.LogLayout, tenantID, tenantName string) (tid, secretKey string, err error)
}

var _tenantCreateAppSDID string

func GetTenantCreateAppSingleton() (*TenantCreateApp, error) {
	if _tenantCreateAppSDID == "" {
		_tenantCreateAppSDID = util.GetSDIDByStructPtr(new(TenantCreateApp))
	}
	i, err := singleton.GetImpl(_tenantCreateAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*TenantCreateApp)
	return impl, nil
}

func GetTenantCreateAppIOCInterfaceSingleton() (TenantCreateAppIOCInterface, error) {
	if _tenantCreateAppSDID == "" {
		_tenantCreateAppSDID = util.GetSDIDByStructPtr(new(TenantCreateApp))
	}
	i, err := singleton.GetImplWithProxy(_tenantCreateAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(TenantCreateAppIOCInterface)
	return impl, nil
}

type ThisTenantCreateApp struct {
}

func (t *ThisTenantCreateApp) This() TenantCreateAppIOCInterface {
	thisPtr, _ := GetTenantCreateAppIOCInterfaceSingleton()
	return thisPtr
}
