version: '3'

services:
  redis:
    image: 'redis'
    restart: always
    container_name: 'redis'
    environment:
      - 'TZ=Asia/Shanghai'
    command: 'redis-server --requirepass clover'
    volumes:
      - './data:/data'
    ports:
      - '6379:6379'
    networks:
      - app_net

networks:
  app_net:
    external: true
